# Name of your quickstart as shown on the website
name: Add the name of your quickstart

# Optional: Authors of the quickstart
authors:
    - Samuel V.
    - Stijn P.

# Optional: Add additional sources as some can't be auto detected by the scripts (for example Prometheus data).
# You can also redirect to external webpages when the dashboards provides specific installation instructions
sources:
  - Prometheus
  - name: CoreDNS
    url: https://github.com/coredns/coredns/tree/master/plugin/metrics
